language: cpp
branches:
  only:
  - master
matrix:
  include:
   - os: linux
     addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
     env:
        - MATRIX_EVAL="eCC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
script:
  - cmake ./
  - make 

 
